# Generated by Django 4.2.1 on 2023-06-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_estoque', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(default='Sem Categoria', max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
    ]
