# Generated by Django 4.2.1 on 2023-06-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=100)),
                ('corredor', models.IntegerField(default=0)),
                ('prateleira', models.IntegerField(default=0)),
                ('nome_produto', models.CharField(max_length=100)),
            ],
        ),
    ]
