# Generated by Django 4.2.1 on 2023-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Compra', 'Compra'), ('Venda', 'Venda')], default='Sem Tipo', max_length=10)),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Financeiro',
            },
        ),
    ]
