# Generated by Django 4.2.1 on 2023-06-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_recursoshumanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='RecursosHumanos',
        ),
    ]
