# Generated by Django 4.2.1 on 2023-06-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_login_delete_cadastro_delete_recursoshumanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('opcoes_funcoes', models.CharField(choices=[('gerente', 'Gerente'), ('caixa', 'Caixa'), ('estoquista', 'Estoquista'), ('administrativo', 'Administrativo')], max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carga_horaria', models.IntegerField()),
                ('folha_de_ponto', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
    ]
