# Generated by Django 4.2.1 on 2023-06-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_cadastro_rh'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RH',
            new_name='RecursosHumano',
        ),
        migrations.RemoveField(
            model_name='login',
            name='last_login',
        ),
    ]
